## Python中的广播

In [2]:
import numpy as np
A = np.array([[56.0, 0.0, 4.4, 68.0],
             [1.2, 104.0, 52.0, 8.0],
             [1.8, 135.0, 99.0, 0.9]])
print A

[[  56.     0.     4.4   68. ]
 [   1.2  104.    52.     8. ]
 [   1.8  135.    99.     0.9]]


### 计算每列的和

In [3]:
cal = A.sum(axis=0)
print cal

[  59.   239.   155.4   76.9]


### 计算百分比

In [5]:
per = A / cal.reshape(1,4)
print per

[[ 0.94915254  0.          0.02831403  0.88426528]
 [ 0.02033898  0.43514644  0.33462033  0.10403121]
 [ 0.03050847  0.56485356  0.63706564  0.01170351]]


### 广播机制的几个例子

In [7]:
a1 = np.array([1, 2, 3, 4]).reshape(4,1)
print a1
print a1 + 100

[[1]
 [2]
 [3]
 [4]]
[[101]
 [102]
 [103]
 [104]]


In [14]:
a2 = np.array(1+np.arange(6)).reshape(2,3)
print a2
print a2 + np.array([100, 200, 300])
print a2 + np.array([100, 200]).reshape(2,1)

[[1 2 3]
 [4 5 6]]
[[101 202 303]
 [104 205 306]]
[[101 102 103]
 [204 205 206]]


## Python Numpy中的向量shape —— 一维数组与行列向量

In [18]:
a = np.random.randn(5)
print a
print a.shape
print a.T
print np.dot(a, a.T)

[ 2.19298187  0.75117019 -0.65155682  0.17783632  1.2642782 ]
(5,)
[ 2.19298187  0.75117019 -0.65155682  0.17783632  1.2642782 ]
7.42797753238


In [19]:
a = np.random.randn(5, 1)
print a
print a.shape
print a.T
print np.dot(a, a.T)

[[-1.06398073]
 [-2.92806257]
 [-0.66202723]
 [-0.33249105]
 [ 1.18185057]]
(5, 1)
[[-1.06398073 -2.92806257 -0.66202723 -0.33249105  1.18185057]]
[[ 1.132055    3.11540216  0.70438422  0.35376407 -1.25746624]
 [ 3.11540216  8.57355041  1.93845716  0.97355458 -3.46053242]
 [ 0.70438422  1.93845716  0.43828006  0.22011813 -0.78241726]
 [ 0.35376407  0.97355458  0.22011813  0.1105503  -0.39295473]
 [-1.25746624 -3.46053242 -0.78241726 -0.39295473  1.39677078]]
